[AuthServer]
BROKER_HOST = rabbitmq-dev
BROKER_PORT = 5672
USER = Phoenix
PASSWORD = StrongPassword
VHOST = Fe-Db
EXCHANGE = UserAuthentication
QUEUE = UserAuth
;EXCHANGE_TYPE = ????

[MovieDBServer]
BROKER_HOST = rabbitmq-dev
BROKER_PORT = 5672
USER = Phoenix
PASSWORD = StrongPassword
VHOST = Fe-Db
EXCHANGE =UserData
QUEUE = Email
AUTO_DELETE = true

[ReviewServer]
BROKER_HOST = rabbitmq-dev
BROKER_PORT = 5672
USER = Phoenix
PASSWORD = StrongPassword
VHOST = Fe-Db
EXCHANGE =UserData
QUEUE = Email
AUTO_DELETE = true

[2FAServer]
BROKER_HOST = rabbitmq-dev
BROKER_PORT = 5672
USER = Phoenix
PASSWORD = StrongPassword
VHOST = Fe-Db
EXCHANGE =UserData
QUEUE = Email
AUTO_DELETE = true


