[AuthServer]
BROKER_HOST = rabbitmq-dev
BROKER_PORT = 5672
USER = Phoenix
PASSWORD = StrongPassword
VHOST = Fe-Db
EXCHANGE = UserAuthentication
QUEUE = UserAuth
;EXCHANGE_TYPE = ????
AUTO_DELETE = true

[2FAServer]
BROKER_HOST = rabbitmq-dev
BROKER_PORT = 5672
USER = Phoenix
PASSWORD = StrongPassword
VHOST = Fe-Db
EXCHANGE =UserData
QUEUE = 2FA
AUTO_DELETE = true


[ReviewServer]
BROKER_HOST = rabbitmq-dev
BROKER_PORT = 5672
USER = Phoenix
PASSWORD = StrongPassword
VHOST = Fe-Db
EXCHANGE =UserData
QUEUE = Reviews
AUTO_DELETE = true

[MovieDBServer]
BROKER_HOST = rabbitmq-dev
BROKER_PORT = 5672
USER = Phoenix
PASSWORD = StrongPassword
VHOST = Fe-Db
EXCHANGE =MovieDatabase
QUEUE = MovieDatabase
AUTO_DELETE = true
~                                
